---
modules-search: [ local ]

instances:
- id:       branding
  module:   branding
  config:   branding.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partitions
  - users
  - summary
- exec:
  - partitions
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - networkcfg
  - hwclock
  - services-systemd
  - bootloader
  - grubcfg
  - mkinitcpio
  - removeuser
  - usersummary
  - preservefiles
  - umount
- show:
  - finish

branding: default
prompt-install: false
dont-chroot: false
