# Custom mkinitcpio.conf for KERNEL FORGE OS
# Removed 'autodetect' to prevent build failures in containerized environments.

MODULES=()
BINARIES=()
FILES=()
HOOKS=(base systemd microcode modconf kms keyboard sd-vconsole block filesystems fsck)
COMPRESSION="zstd"
