---
componentName:  default

welcomeStyleCalamares:   false
welcomeExpandingLogo:   true
windowExpanding:         normal
windowSize: 800,600
windowPlacement: center

strings:
    productName:         KERNEL FORGE OS
    shortProductName:    KERNEL FORGE
    version:             1.0.0
    shortVersion:        1.0.0
    versionedName:       KERNEL FORGE OS 1.0.0
    shortVersionedName:  KERNEL FORGE 1.0.0
    bootloaderEntryName: KERNEL FORGE OS
    productUrl:          https://github.com/Archlord12345/KERNEL-FORGE-OS
    supportUrl:          https://github.com/Archlord12345/KERNEL-FORGE-OS/issues
    knownIssuesUrl:      https://github.com/Archlord12345/KERNEL-FORGE-OS/issues
    releaseNotesUrl:     https://github.com/Archlord12345/KERNEL-FORGE-OS
    donateUrl:           https://github.com/Archlord12345/KERNEL-FORGE-OS

images:
    productLogo:         "/usr/share/backgrounds/kernel-forge/deepin.png"
    productIcon:         "/usr/share/backgrounds/kernel-forge/deepin.png"
    productWelcome:      "/usr/share/backgrounds/kernel-forge/kernel_forge_wallpaper_v2.png"

style:
   sidebarBackground:    "#292F34"
   sidebarText:          "#FFFFFF"
   sidebarTextSelect:    "#292F34"
   sidebarTextHighlight: "#3DAEE9"
